#!/usr/bin/env python
import sys
def count(argv):
    filename = argv[1]
    f = open(filename, 'r')
    str = f.read()

    array = [0, 0, 0, 0]

    for c in str:
        if c == 'A':
            array[0] += 1
        elif c == 'C':
            array[1] += 1
        elif c == 'G':
            array[2] += 1
        elif c == 'T':
            array[3] += 1

    print array





if __name__ == '__main__':
    #str = 'TCATCAAATAGTAACATGTTGGGCCGCAAAAGCATGCCCGTCTTTAGTGTATGTTTACCATAGCGTCACTTGTAATCTTGGCTCGCCGACTCGACAGTATCTCCTCGCGTCTTGGCTATCGACCGGTAAAGAATTACCTGGCGGTAGACCCCAGTGGAGAATTGTGCCATCAAAGGAGACATATACTACAGGTGACCGGAAAGACGCGCCGTAACGCTCGATGAGCCGCAGAGAGAGTCGCCAGACGCTGAACTGTGTTGCGCAGCATGATAACTCGCGAATGGAGTTTACAGAATTATGTGTAGCGGCGCGTCATATCACACGGATGCATACACCTCTTTACATGCGGGGGCTTACAGTAGCGCTTTATTCTAGATGACTTTAAGGAAGAGCCCCGTGGAGCCTAGACGATTGGCCCAATATTGAAAAACCACATCCTAGTTCCCAGTGTGCCCACGCGGGGTCGGCGTTGAGACCTCGTGGCGTCACATAGCAGGATACGCACTGCAGGCCTAGTGGCCTACAGGACAGATTTCGTGGGGGGCATCATGCCTTGGGACGGAGAGCAGTGCACTGAACTGCTCGTGACCTTGACGGTGGTTACGCTTTAGCATATGAAAAACTGCATACCTGTCGGCGTAGTATACTGCTACCTTGTGGTAGGTACGGTTACCCCACGACACCTTCACCCGTGGGAAGCCCTAATCTATACAGTGCGTATGCTGATAGCCAGACACCTCGTTGTTAGACTGCAAGCCCGAGGGTACGAGCGATTAGGGTTGTCCATAGCCTCGTGGCCCGCTGACCCCTCAGGGTGTATGAACGTGGAGGTTGCTGGGAG'
    count(sys.argv)

